// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfu28pq2SsYo6FMqepsQOs1lTv4XjKISw',
    appId: '1:661572306201:web:f6a5cb3440a8401951f188',
    messagingSenderId: '661572306201',
    projectId: 'hotelio-f03d4',
    authDomain: 'hotelio-f03d4.firebaseapp.com',
    storageBucket: 'hotelio-f03d4.appspot.com',
    measurementId: 'G-SLK89XKFHL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpwiOBFQd-3Zkvc6GlytDrCdNJTSHy3xo',
    appId: '1:661572306201:android:db5781645b9790dd51f188',
    messagingSenderId: '661572306201',
    projectId: 'hotelio-f03d4',
    storageBucket: 'hotelio-f03d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjgMQopwQfBWPeEVoAJDQenJmLhM6uSow',
    appId: '1:661572306201:ios:bcb6b3fdc737cc6751f188',
    messagingSenderId: '661572306201',
    projectId: 'hotelio-f03d4',
    storageBucket: 'hotelio-f03d4.appspot.com',
    iosClientId: '661572306201-sd7eaoo9uhkapm6rcljmsss6o5vipodp.apps.googleusercontent.com',
    iosBundleId: 'com.example.hotelioApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjgMQopwQfBWPeEVoAJDQenJmLhM6uSow',
    appId: '1:661572306201:ios:39b8fef2fb12c7a651f188',
    messagingSenderId: '661572306201',
    projectId: 'hotelio-f03d4',
    storageBucket: 'hotelio-f03d4.appspot.com',
    iosClientId: '661572306201-en3eud629relcjefd9nbfe0k0bvudg51.apps.googleusercontent.com',
    iosBundleId: 'com.example.hotelioApp.RunnerTests',
  );
}
